### ISSUE TITLE
Missing AWS Provider Alias "use_default_region"

### ISSUE THREAD

**Issue by onurbolukbas** [alazaroc/aws-terraform-serverless-website#1]
Before I begin, I would like to thank you for your article related to this repository.

I'm encountering an issue in my Terraform configuration where I'm trying to use the AWS provider alias "use_default_region" (aws.use_default_region) for resource definition. However, there is no corresponding provider block with this alias defined in the Terraform configuration.

Steps to Reproduce:

In my Terraform configuration, I have a resource block that references the "use_default_region" alias:

```
resource "aws_acm_certificate" "cert" {
  provider                  = aws.use_default_region
  domain_name               = "*.${var.domain_name_simple}"
  validation_method         = "DNS"
  subject_alternative_names = [var.domain_name_simple]

  lifecycle {
    create_before_destroy = true
  }
}
```

resource "aws_acm_certificate" "cert" {
  provider                  = aws.use_default_region
  domain_name               = "*.${var.domain_name_simple}"
  validation_method         = "DNS"
  subject_alternative_names = [var.domain_name_simple]

  lifecycle {
    create_before_destroy = true
  }
}
When running Terraform, I receive an error indicating that the provider configuration is not present.

Suggested Fix:
Define the AWS provider block with the alias "use_default_region" in the Terraform configuration with the appropriate settings and credentials for the desired AWS region.

Screenshots:
![image](https://github.com/alazaroc/aws-terraform-serverless-website/assets/40565125/6413b5f4-d4b4-4462-944d-22743dc2b33f)

**Comment by alazaroc** [comment]
Hi @onurbolukbas, I couldn't check your message properly before. 

You are right, in my v3 code is missing the definition of the second provider, I just added it! Thanks for letting me know!

# Special provider for creating ACM certs as they must be provisioned in us-east-1 to work with 
```
provider "aws" {
  region = "us-east-1"
  alias  = "use_default_region"
}
```

**Comment by onurbolukbas** [comment]
You're welcome. I am closing the issue as it's resolved.
